storage:
  type: LiteSQL # LiteSQL (local storage), MySQL, MariaDB, MongoDB
  host: "localhost"
  port: 3306
  database: "database_name"
  username: "root"
  password: ""
  save-delay: 300

general:
  config-version: 2
  use-worldguard: false #works only for Worldguard 7+
  topscore-limit: 10

locale:
  lang: "en_EN"
  decimal-display: 2 #The number of digits behind Karma amounts on display (does not affect storage or calculations)
  title: #Duration of the title in ticks (20ticks = 1 second)
    fade-in: 1
    stay: 20
    fade-out: 1

karma:
  default: 0
  minimum: -30000
  maximum:  15000

tiers:
  list:
    devil: #an out of bound tier useful for perma-criminal players
      display: "&l{#FF0000}DEVIL"
      short-display: "&l{#FF0000}⛧"
      minimum: -500000 #Out of bounds
      default-karma: -45000
      maximum: -30000.01 #2 digits accuracy
      # no score.
      commands:
        on-join:
          - "player[msg-title] [player_tier_display_short]You are now doomed."
          - "karma edit player [player] wanted add 99h -o" #-o to override the limit
    criminal:
      display: "&4Criminal"
      short-display: "&4"
      minimum: -30000
      default-karma: -25000
      maximum: -15000
      score:
        devil: 40
        criminal: 25
        thug: 5
        citizen: -20
        vigilante: -70
        sheriff: -150
      commands:
        on-join:
          - "broadcast &f[player] is now a notorious [player_tier_display]&r."
        on-join-down:
          - "karma edit player [player] wanted add 2h -o" #-o to override the limit
        on-join-up:
          - "player[msg] The god admin gave you one more chance. Do not waste it this time."
    thug:
      display: "&5Thug"
      short-display: "&5"
      minimum: -14999.99
      maximum: -500
      score:
        devil: 45
        criminal: 35
        citizen: -10
        vigilante: -40
        sheriff: -150
      commands:
        on-join:
          - "player[msg] &fYou are now a filthy [player_tier_display]&r."
        on-join-down:
          - "karma edit player [player] wanted add 30m -o" #-o to override the limit
          - "player[msg] &bThe police is now hunting you."
        on-join-up:
          - "player[msg] &aKeep a low profile."
    citizen:
      display: "&fCitizen"
      short-display: "&f"
      minimum: -499.99
      maximum: 9999.99
      score:
        devil: 50
        criminal: 25
        citizen: -20
        vigilante: -40
        sheriff: -150
      commands:
        on-join:
          - "player[msg] &fYou are a [player_tier_display]&r."
          - "bc [evalformat_[player_karma]+10] karma +10 formatted"
          - "player[msg-actionbar] &fYour previous Tier was [player_previous_tier_display] and the previous karma was [player_previous_karma]"
    vigilante:
      display: "&aVigilante"
      short-display: "&a"
      minimum: 10000
      default-karma: 11000
      maximum: 13999.99
      score:
        devil: 55
        criminal: 30
        thug: 8
        citizen: -25
        vigilante: -60
        sheriff: -150
      commands:
        on-join:
          - "player[msg] &fYour are a [player_tier_display]&r."
          - "bc [eval_[player_karma]*50] karma * 50 Double"
        on-join-up:
          - "player[msg] &bYou can help the police now."
        on-join-down:
          - "player[msg] &bYou have been demoted from the police forces."
    sheriff:
      display: "&6Sheriff"
      short-display: "&6"
      minimum: 14000
      default-karma: 14100
      maximum: 15000
      score:
        devil: 60
        criminal: 20
        thug: 5
        citizen: -50
        vigilante: -70
        sheriff: -200
      commands:
        on-join:
          - "player[msg] &fYour wanted level is now [player_tier_display]&r."
          - "bc [evalfloat_[player_karma]/2] karma /2 float"
        on-join-up:
          - "player[msg] &bYou are got promoted from [player_previous_tier_display]&r."
    paragon:
      display: "&l&bParagon"
      short-display: "&l&b⚖"
      minimum: 15000.01
      maximum: 50000
      commands:
        on-join:
          - "[title] [player_tier_display]"
          - "player[msg] &fYou are so good that you are not limited by the law"

wanted:
  #if a player attacks another one, everybody can strike him back without karma changes (unless if the defender is wanted too)
  enable: true
  countdown-on-disconnect: true
  #[player_wanted_time] use the highest amount between the player's wanted time and the actual timestamp.
  maximum-duration: "[now] 8h" #compatible with: d h m s
  commands:
    enter:
      - "bc [player] is now [player_wanted_status_short]WANTED"
      - "player[msg] You are now [player_wanted_status] for [player_wanted_time_delay_display]"
    refresh:
      - "bc [player] is STILL [player_wanted_status_short]WANTED"
      - "player[msg] You still [player_wanted_status] for [player_wanted_time_delay_display]"
    exit:
      - "bc [player] is now INNOCENT"
      - "player[msg] You are now [player_wanted_status]"

worlds:
  enable: false #if enabled, only the worls listed below will be used
  black-list: false #if true, the worlds on the list will not be used
  worlds:
    - world

pvp:
  # You can make your own expression, any error will lead to a result of 0.
  hit-attacker-change-expression: "([victim_karma_abs] + 200) * [attacker_victim_tier_score] / 50"
  kill-attacker-change-expression: "([victim_karma_abs] + 200) * [attacker_victim_tier_score] / 10"
  hit-victim-change-expression: "([attacker_karma_abs] + 100) * [victim_attacker_tier_score] / 100" #does not trigger wanted
  kill-victim-change-expression: "([attacker_karma_abs] + 100) * [victim_attacker_tier_score] / 20" #does not trigger wanted
  team-system-cancel:
    scoreboard-team: #Default scoreboard team in minecraft
      enable: true
      same-team: true #cancel if players in the same scoreboard team
      other-team: false
  messages-delay: #seconds
    hit: 5
    kill: 10
  wanted:
    hit-duration: "[player_wanted_time] 5m 15s" #compatible with: d h m s
    kill-duration: "[player_wanted_time] 1h 30m" #compatible with: d h m s
    requirements:
      on-karma-gain: false
      on-karma-unchanged: false
      on-karma-loss: true
      refresh: true
    cancel-karma-change:
      wanted:
        on-karma-gain: true
        on-karma-loss: false
      innocent:
        on-karma-gain: false
        on-karma-loss: true
  commands:
    kill:
      #command-name:
      #  requirements: # any requirement is ignored if empty
      #    guarantee: <boolean> # default true. If true, commands are sent before checking time periods and worldguard regions. Else, triggers if time periods and worldguard region check are good.
      #    attacker-tier :
      #      - "tierName" #first lines with "!tierName" to use all tiers BUT.
      #    victim-tier:
      #      - "etc"
      #    attacker-status: <String> #WANTED / INNOCENT
      #    victim-status: <String> #WANTED / INNOCENT
      #    attacker-minimum-karma: <float>
      #    attacker-maximum-karma: <float>
      #  commands:
      #    - ""
      #    -  "etc..."
      bad-boy-kills-someone: #Only triggers if a thug got killed, no matter the attacker tier or victim status. The event must not be cancelled because of worldguard region or system/world time period
        requirements:
          guarantee: false
          attacker-tier:
            - "criminal"
            - "thug"
        commands:
          - "cmi money give [attacker] 1%[100-500][[victim]]" #Gives up to 1] of the victim money, minimum 100, maximum 500.
          - "cmi money take [victim] 2%[200-1000]" #Removes up to 2] of the victim money, minimum 200, maximum 1000, always superior to the give command.
      police-arrest-wanted-criminal: #Only triggers when an INNOCENT SHERIFF or a INNONCENT VIGILANTE kills a WANTED CRIMINAL
        requirements:
          attacker-tier:
            - "sheriff"
            - "vigilante"
          attacker-status: "INNOCENT"
          victim-tier:
            - "criminal"
          victim-status: "WANTED"
        commands:
          - "jail [victim] jail [evalint_[victim_karma_abs]/1000]m"
          - "bc [evalint_[victim_karma_abs]/1000]m karma_abs/1000 int"
          - "broadcast [victim] &ahas been arrested for [evalint_[victim_karma_abs]/1000] minutes by [attacker] !"

pve:
  messages-delay:
    hit: 5
    kill: 10
  list:
    #default entities names
    Ender Dragon:
      kill-karma-reward: 10000
      kill-commands:
        - "bc [player] &aKILLED THE ENDERDRAGON, GG !!!"
    Cat:
      hit-karma-reward:    -10
      hit-message: "&cYou DARE put a hand on your Master ?!!"
      kill-karma-reward:   -76
      kill-message: "&4&lWILFRIIIIIIIED !!!"
    Trader Llama:
      hit-karma-reward:    -11
      kill-karma-reward:  -356
    Wolf:
      hit-message: "Hunt a wolf doesn't change your karma : &d[attacker_karma]"
      kill-message: "You successfully hunt the wolf : &5[attacker_karma]"
    Zombie:
      hit-karma-reward:      5
      hit-message: "Aim his head !"
      kill-karma-reward:    58
      kill-message: "Burn the corpse."
    #renamed entities
    Galsia:
      hit-karma-reward: 3
      hit-message: "HIT !"
      kill-karma-reward: 8

time-periods:
  #NONE Doesn't check any time period
  #WORLD Use attacker world time periods
  #SYSTEM Use server time period
  #BOTH use both and cumulate.
  type: "NONE"
  world:
    dawn:
      start: "05:00" #format hh:mm 24h
      end: "08:59"
      rate: 100 # chances of karma change. between 0 and 100
    day:
      start: "09:00"
      end: "19:59"
      rate: 100
    dusk:
      start: "20:00"
      end: "21:59"
      rate: 66
    night:
      start: "22:00"
      end: "04:59"
      rate: 30
  system:
    morning:
      start: "08:00" #format hh:mm 24h
      end: "12:59"
      rate: 100
    afternoon:
      start: "13:00"
      end: "21:00"
      rate: 30

overtime:
  enable: true
  loops:
    #loopName: #name it however you want
    #  timers:
    #    first: <long> # First timer, generally longer or equal to the NEXT.
    #    next: <long>  # Timer after first occurence. Generally shorter or equal
    #  requirements:
    #    karma:
    #      minimum: <float> #Ignored if empty
    #      maximum: <float> #ignored if empty
    #    online: <boolean> #true by default
    #    offline: <boolean> #false by default
    #  amount: <float> #0 by default. If offline is true, applies for every delay reached
    #  commands: <String[]> #ignored if empty. If offline is true, applies only once on reconnection.
    online-positive-1min-then-10sec:
      timers:
        first: 60
        next: 10
      requirements:
        karma:
          minimum: 0
          maximum: 15000
      amount: -5
      commands:
        - "player[msg] Removed 5 karma, 1 minute then 10 seconds."
    15min:
      timers:
        first: 900
      requirements:
        karma:
          maximum: 0
        offline: true
      commands:
        - "player[msg] Trigger every 15 minutes connected or not, only once if reconnect after long time."
    offline-only-negative-hourly:
      timers:
        first: 3600
      requirements:
        karma:
          maximum: 0
        online: false
        offline: true
      amount: 50
      commands:
        - "player[msg] Added [player_karma_diff] karma, hourly until you reach 0 karma if disconnected only."

blocks:
  list:
    # https://minecraft-ids.grahamedgecombe.com/
    # Be careful to use the blocks name, not the item (carrot for item, CARROTS for block)
    WHEAT: #section name, can be block name
      break:
        data:
          age: #useful on crops
            blacklist: true
            ages:
              - 7
        value: -5
        reset-overtime: true #Don't mess with the cultures !
    yellow_or_red_wool:
      regex: "(RED|YELLOW)_WOOL" #regex. Replace block/section name.
      place:
        value: 1
    all_logs:
      regex: "*LOG" #* equals '(\w+)?' , it means "any characters"
      break:
        value: -0.1
    FIRE:
      place: #place fire (flint, fireball)
        value: -5
        reset-overtime: true #Reset all the player overtimes timers. Default to false
      break: #Hit fire
        value: 2

shops:
  list:
    first:
      display: "&aFirst"
      description: "&fFirst Shop. Usable by player"
      price: 1000.0
      cost-reset-overtime: false
      min-karma: 1000
      send-by: PLAYER #PLAYER / CONSOLE / BOTH
      commands:
        - "bc [player] bought the first item from karma shop !"
    second:
      display: "&9First"
      description: "&fSecond Shop. Not usable by player"
      price: -500.0
      cost-reset-overtime: false
      max-karma: -500
      send-by: CONSOLE #PLAYER / CONSOLE / BOTH
      commands:
        - "bc [player] bought the second item from karma shop !"