storage:
  type: LOCALSTORAGE # LocalStorage, SQL, MariaDB, MongoDB, LiteSQL
  host: "localhost"
  port: 3306
  database: "database_name"
  username: "root"
  password: ""
  save-delay: 300

general:
  lang: "en_EN"
  decimal-display: 2 #The number of digits behind Karma amounts on display (does not affect storage or calculations) # => locale file
  title: #Duration of the title in ticks (20ticks = 1 second)
    fade-in: 1
    stay: 20
    fade-out: 1
  use-worldguard: false #works only for Worldguard 7+
  datetime-format: "yyyy-MM-dd HH:mm:ss" # => locale file
  countdown-format: "{dd} {HH}:{mm}:{ss}" #use dd, d, hh, h, mm, m, ss, s between {} without cap. => locale file
  debug-mode: false
  topscore-limit: 10

karma:
  default:     0
  minimum: -3000
  maximum:  1500

worlds:
  enable: false #if enabled, only the worls listed below will be used
  black-list: false #if true, the worlds on the list will not be used
  worlds:
    - world

overtime:
  enable: true
  loops:
    #loopName: #name it however you want
    #  timers:
    #    first: <long> # First timer, generally longer or equal to the NEXT.
    #    next: <long>  # Timer after first occurence. Generally shorter or equal
    #  requirements:
    #    karma:
    #      minimum: <float> #Ignored if empty
    #      maximum: <float> #ignored if empty
    #    online: <boolean> #true by default
    #    offline: <boolean> #false by default
    #  amount: <float> #0 by default. If offline is true, applies for every delays reached
    #  commands: <String[]> #ignored if empty. If offline is true, applies only once on reconnection.
    online-citizen:
      timers:
        first: 3600
        next: 1800
      requirements:
        karma:
          minimum: 500
      amount: -50
      commands:
        - "%msg% Removed 50 karma, hourly."
    offline-citizen:
      timers:
        first: 43200
      requirements:
        online: false
        offline: true
        karma:
          minimum: 500
      amount: -250
      commands:
        - "%msg% Removed %karma_player_diff_karma% karma, offline only and daily."
    online-criminal:
      timers:
        first: 3600
        next: 1800
      requirements:
        karma:
          maximum: -1500
      amount: 25
      commands:
        - "%msg% Added 25 karma. Online only, hourly then mid-hourly)."
    offline-criminal:
      timers:
        first: 43200
      requirements:
        online: false
        offline: true
        karma:
          maximum: -1500
      amount: 125
      commands:
        - "%msg% Added %karma_player_diff_karma% karma (offline only, daily)."

tiers:
  none-display: "&f[&8None&f]&r"
  none-short-display: "&f"
  list:
    criminal:
      display: "&4Criminal"
      short-display: "&4"
      minimum: -3000
      maximum: -1500
      punish-wanted: true
      score:
        criminal: 50
        thug: 5
        citizen: -20
        vigilante: -70
        sheriff: -150
      commands:
        join-commands:
          - "broadcast &f%player% is now the most wanted %karma_player_tier_display% &r."
        join-on-down-commands:
          - "%msg-title% {#FF0000}&lWANTED
          %msg-subtitle%&cEverybody is now trying to kill you."
        killed-commands:
          sheriff:
            - "jail %victim% jail %karma_victim_karma%"
            - "karma set %victim% -3000"
            - "broadcast %victim% &ahas been arrested for %karma_victim_previous_karma% minutes by %attacker% !"
    thug:
      display: "&5Thug"
      short-display: "&5"
      minimum: -1499
      maximum: -50
      punish-wanted: false
      score:
        criminal: 35
        citizen: -10
        vigilante: -40
        sheriff: -150
      commands:
        join-commands:
          - "%msg% &fYou are now a filthy %karma_player_tier% &r."
          - "%msg% me &5is now in the dark side of the law."
        join-on-down-commands:
          - "%msg% &bThe police is now hunting you."
        join-on-up-commands:
          - "%msg% &aKeep a low profile."
        killed-commands:
          commands:
            - "jail %victim% jail %karma_victim_karma%"
            - "karma set %victim% -1499"
            - "broadcast %victim% loss a fight against %attacker% with the tier identifier %karma_attacker_tier%!"
    citizen:
      display: "&fCitizen"
      short-display: "&f"
      minimum: -49
      maximum: 500
      punish-wanted: false
      score:
        criminal: 40
        citizen: -20
        vigilante: -40
        sheriff: -150
      commands:
        join-commands:
          - "%msg% &fYou are a %karma_player_tier_display% &r."
          - "%msg-actionbar% &fYour previous Tier was %karma_player_previous_tier_display% and the previous karma was %karma_player_previous_karma%"
    vigilante:
      display: "&aVigilante"
      short-display: "&a"
      minimum: 501
      maximum: 1250
      punish-wanted: false
      score:
        criminal: 30
        thug: 8
        citizen: -25
        vigilante: -60
        sheriff: -150
      commands:
        join-commands:
          - "%msg% &fYour are a %karma_player_tier_display% &r."
        join-on-up-commands:
          - "%msg% &bYou can help the police now."
        join-on-down-commands:
          - "%msg% &bYou have been demoted from the police forces."
        killed-commands:
          commands:
            - "attacker %msg% You killed a %karma_victim_tier_display%, you got %karma_attacker_diff_karma% karma"
    sheriff:
      display: "&6Sheriff"
      short-display: "&6"
      minimum: 1251
      maximum: 1500
      punish-wanted: true
      score:
        criminal: 20
        thug: 5
        citizen: -50
        vigilante: -70
        sheriff: -200
      commands:
        join-commands:
          - "%msg% &fYour wanted level is now %karma_player_tier_display% &r."
        join-on-up-commands:
          - "%msg% &bYou are got promoted from %karma_player_previous_tier_display%."
        killed-commands:
          commands:
            - "broadcast %victim% has been assassinated by %attacker% with %karma_attacker_previous_karma% karma before the act."
          criminal:
            - "victim %msg% %attacker% was in Criminal tier when he killed you."

times:
  use-both-system-and-worlds-time: "NONE" #can be replaced by WORLDS, SYSTEM and BOTH or NONE
  #NONE Doesn't check time
  #WORLDS Check only the worlds-time
  #SYSTEM Check only the server/system time
  #BOTH check WORLDS AND SYSTEM. both must be TRUE.
  worlds-times: #use the time where the attacker / killer is You can add all the time-X you want with custom name
    day:
      start-time: "09:00"
      end-time: "20:00"
      rate: 100
    dusk:
      start-time: "20:00"
      end-time: "22:00"
      rate: 66
    night:
      start-time: "22:00"
      end-time: "01:00"
      rate: 30
  system-times: #use the server real life time. You can add all the time-X you want, with custom name
    morning:
      start-time: "08:00"
      end-time: "12:59"
      rate: 100
    afternoon:
      start-time: "13:00"
      end-time: "21:00"
      rate: 30

pvp:
  # You can make your own expression, any error will lead to a result of 0.
  hit-reward-expression: "-1 * (%karma_victim_karma% + 200) / 50"
  kill-reward-expression: "-1 * (%karma_victim_karma% + 200) / 10"
  team-system-cancel:
    scoreboard-team: #Default scoreboard team in minecraft
      enable: true
      same-team: true
      other-team: false
  messages-delay:
    hit: 5
    kill: 10
  wanted: #if a player attacks another one, everybody can strike him back without karma changes (unless if the defender is wanted too)
    enable: true
    countdown-on-disconnect: true
    #%player_wanted_time% use the highest amount between the player's wanted time and the actual timestamp.
    hit-duration: "%player_wanted_time% 5m" #compatible with: d h m s ms
    kill-duration: "%player_wanted_time% 15m" #compatible with: d h m s ms
    max-duration: "%now% 8h" #compatible with: d h m s ms
    conditions:
      on-karma-gain: false
      on-karma-unchanged: false
      on-karma-loss: true
      refresh: true
    cancel-karma-change:
      wanted:
        on-karma-gain: true
        on-karma-loss: false
      innocent:
        on-karma-gain: false
        on-karma-loss: true
    commands:
      enter:
        - "bc %player% is now WANTED"
      refresh:
        - "bc %player% is STILL WANTED"
      exit:
        - "bc %player% is now INNOCENT"
      punish:
        - "bc %victim% has been arrested by %attacker% !"
        - "bc Jailed now !"

entities:
  messages-delay:
    hit: 5
    kill: 10
  list:
    #default entities names
    Ender Dragon:
      kill-karma-reward: 10000
      kill-commands:
        - "bc %player% &aKILLED THE ENDERDRAGON, GG !!!"
    Cat:
      hit-karma-reward:    -10
      hit-message: "&cYou DARE put a hand on your Master ?!!"
      kill-karma-reward:   -76
      kill-message: "&4&lWILFRIIIIIIIED !!!"
    Trader Llama:
      hit-karma-reward:    -11
      kill-karma-reward:  -356
    Wolf:
      hit-message: "Hunt a wolf doesn't change your karma : &d%karma_attacker_karma%"
      kill-message: "You successfully hunt the wolf : &5%karma_attacker_karma%"
    Zombie:
      hit-karma-reward:      5
      hit-message: "Aim his head !"
      kill-karma-reward:    58
      kill-message: "Burn the corpse."
    #renamed entities
    Galsia:
      hit-karma-reward: 3
      hit-message: "HIT !"
      kill-karma-reward: 8

blocks:
  list:
    # https://minecraft-ids.grahamedgecombe.com/
    # Be careful to use the blocks name, not the item (carrot for item, CARROTS for block)
    WHEAT:
      break:
        data:
          age:
            blacklist: true
            ages:
              - 7
        value: -5
        reset-overtime: true #Don't fuck with the cultures !
    FARMLAND:
      place: #Using a hoe to transform dirt to farmland
        value: 1
    TNT:
      place:
        value: -100
        reset-overtime: true #Reset all the player overtimes timers. Default to false
      break:
        value: 10
    FIRE:
      place: #place fire (flint, fireball)
        value: -5
        reset-overtime: true #Reset all the player overtimes timers. Default to false
      break: #Hit fire
        value: 2
    

shops:
  list:
    first:
      display: "&aFirst"
      description: "&fFirst Shop. Usable by player"
      price: 1000.0
      cost-reset-overtime: false
      min-karma: 1000
      send-by: PLAYER #PLAYER / CONSOLE / BOTH
      commands:
        - "bc %player% bought the first item from karma shop !"
    second:
      display: "&9First"
      description: "&fSecond Shop. Not usable by player"
      price: -500.0
      cost-reset-overtime: false
      max-karma: -500
      send-by: CONSOLE #PLAYER / CONSOLE / BOTH
      commands:
        - "bc %player% bought the second item from karma shop !"