name: Karma
version: ${project.version}
description: Make your players actions have consequences !
api-version: 1.15
author: Rosstail
website: https://www.spigotmc.org/resources/karma.76077
softdepend:
  - WorldGuard
  - PlaceholderAPI
main: com.rosstail.karma.Karma
commands:
  karma:
    description: Karma plugin by Rosstail
    usage: /karma
    permission: karma
    permission-message: You don't have permission !

permissions:
  karma:
    default: true
  karma.help:
    default: true
  karma.self:
    default: true
  karma.other:
    default: op
  karma.set:
    default: op
  karma.add:
    default: op
  karma.remove:
    default: op
  karma.reset:
    default: op
  karma.calculate:
    default: op
  karma.wanted.self:
    default: true
  karma.wanted.other:
    default: op
  karma.wanted.set:
    default: op
  karma.wanted.add:
    default: op
  karma.wanted.remove:
    default: op
  karma.wanted.reset:
    default: op
  karma.save:
    default: op
  karma.immune:
    default: false
  karma.*:
    default: false
    description: Gives all karma plugin permissions
    children:
      karma: true
      karma.help: true
      karma.self: true
      karma.other: true
      karma.set: true
      karma.add: true
      karma.remove: true
      karma.reset: true
      karma.calculate: true
      karma.wanted.self: true
      karma.wanted.other: true
      karma.wanted.set: true
      karma.wanted.add: true
      karma.wanted.remove: true
      karma.wanted.reset: true
      karma.save: false
      karma.immune: false