name: Karma
version: ${project.version}
description: Make your players actions have consequences !
api-version: 1.15
author: Rosstail
website: https://www.spigotmc.org/resources/karma.76077
softdepend:
  - WorldGuard
  - PlaceholderAPI
main: com.rosstail.karma.Karma
commands:
  karma:
    description: Karma plugin by Rosstail
    usage: /karma
    permission: karma.command
    permission-message: You don't have permission !

permissions:
  karma.command:
    default: true
  karma.command.help:
    default: true
  karma.command.calculate:
    default: op
  karma.command.save:
    default: op
  karma.immune:
    default: false

  karma.command.check:
    default: true
  karma.command.check.self:
    default: true
  karma.command.check.other:
    default: op
  karma.command.check.*:
    default: op
    children:
      karma.command.check: true
      karma.command.check.self: true
      karma.command.check.other: true

  karma.command.shop:
    default: true
  karma.command.shop.self:
    default: true
  karma.command.shop.other:
    default: op
  karma.command.shop.*:
    default: op
    description: Gives all shop commands permission
    children:
      karma.command.shop: true
      karma.command.shop.self: true
      karma.command.shop.other: true

  karma.command.edit.player.karma:
    default: op
  karma.command.edit.player.tier:
    default: op
  karma.command.edit.player.wanted:
    default: op
  karma.command.edit.player.*:
    default: op
    children:
      karma.command.edit.player.karma: true
      karma.command.edit.player.tier: true
      karma.command.edit.player.wanted: true

  karma.command.edit.*:
    default: op
    children:
      karma.command.edit.player.*: true

  karma.command.*:
    default: op
    description: Gives all commands permissions
    children:
      karma.command: true
      karma.command.calculate: true
      karma.command.help: true
      karma.command.edit.*: true
      karma.command.save: true
      karma.command.check.*: true
      karma.command.shop.*: true
  karma.*:
    default: false
    description: Gives all karma plugin permissions
    children:
      karma.command.*: true
      karma.immune: true