name: Karma
version: 1.9.0
description: Make your players actions have consequences !
api-version: 1.15
author: Rosstail
website: https://www.spigotmc.org/resources/karma.76077
softdepend:
  - WorldGuard
  - PlaceholderAPI
main: com.rosstail.karma.Karma
commands:
  karma:
    description: Karma plugin by Rosstail
    usage: /karma
    permission: karma
    permission-message: You don't have permission !
  karma help:
    description: Displays list of plugin commands
    usage: /karma help
    permission: karma.help
    permission-message: You don't have permission !
  karma check:
    description: Check karma of a player
    usage: /karma
    permission: karma.own
    permission-message: You don't have permission !
  karma set:
    description: Set the karma of a player
    usage: /karma set [player] [amount]
    permission: karma.set
    permission-message: You don't have permission !
  karma add:
    description: Add specified amount of a player karma
    usage: /karma add [player] [amount]
    permission: karma.add
    permission-message: You don't have permission !
  karma remove:
    description: Remove specified amount of a player karma
    usage: /karma remove [player] [amount]
    permission: karma.remove
    permission-message: You don't have permission !
  karma reset:
    description: Set player's karma to default
    usage: /karma [player] reset
    permission: karma.reset
    permission-message: You don't have permission !
  karma save:
    description: Saves all datas from players connected
    usage: /karma save
    permission: karma.save
    permission-message: You don't have permission !
  karma calculate:
    description: Calculate a mathematical formula
    usage: /karma [expression]
    permission: karma.calculate
    permission-message: You don't have permission !

permissions:
  karma:
    default: true
  karma.help:
    default: true
  karma.own:
    default: true
  karma.other:
    default: false
  karma.set:
    default: op
  karma.add:
    default: op
  karma.remove:
    default: op
  karma.reset:
    default: op
  karma.calculate:
    default: false
  karma.save:
    default: op
  karma.*:
    default: op
    description: Gives all karma plugin permissions
    children:
      karma: true
      karma.help: true
      karma.own: true
      karma.other: true
      karma.set: true
      karma.add: true
      karma.remove: true
      karma.reset: true
      karma.calculate: true