name: Karma
version: ${project.version}
description: Make your players actions have consequences !
api-version: 1.15
author: Rosstail
website: https://www.spigotmc.org/resources/karma.76077
softdepend:
  - WorldGuard
  - PlaceholderAPI
main: com.rosstail.karma.Karma
commands:
  karma:
    description: Karma plugin by Rosstail
    usage: /karma
    permission: karma.command
    permission-message: You don't have permission !

permissions:
  karma.command:
    default: true
  karma.command.help:
    default: true
  karma.command.shop.self:
    default: true
  karma.command.shop.other:
    default: op
  karma.command.check.self:
    default: true
  karma.command.check.other:
    default: op
  karma.command.edit:
    default: op
  karma.command.calculate:
    default: op
  karma.command.check.save:
    default: op
  karma.command.wanted.self:
    default: true
  karma.command.wanted.other:
    default: op
  karma.command.wanted.edit:
    default: op
  karma.immune:
    default: false
  karma.command.*:
    default: op
    description: Gives all commands permissions
    children:
      karma.command: true
      karma.command.calculate: true
      karma.command.help: true
      karma.command.check.self: true
      karma.command.check.other: true
      karma.command.shop.self: true
      karma.command.shop.other: true
      karma.command.edit: true
      karma.command.save: true
      karma.command.wanted.self: true
      karma.command.wanted.other: true
      karma.command.wanted.edit: true
  karma.*:
    default: false
    description: Gives all karma plugin permissions
    children:
      karma.command.*: true
      karma.immune: true